import localFont from 'next/font/local';
import "./globals.css";
import Nav from './components/Nav';

const roobert = localFont({
  src: [
    {
      path: './fonts/RoobertTRIAL-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/RoobertTRIAL-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/RoobertTRIAL-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/RoobertTRIAL-Light.otf',
      weight: '300',
      style: 'normal',
    },
  ],
  variable: '--font-roobert', 
  display: 'swap', 
});

export const metadata = {
  title: "Skinstric | Home",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roobert.variable} font-sans`}>
      <body className="min-h-screen flex flex-col">
        <Nav />
        <div className="flex-1 flex flex-col justify-center relative">
          {children}
        </div>
      </body>
    </html>
  );
}
